# Application
spring.application.name=retail-management
server.port=8080

#spring.jpa.hibernate.ddl-auto=create-drop
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.liquibase.drop-first=false
spring.jpa.properties.hibernate.use_sql_comments=true

#logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.yourpackage=DEBUG
# JPA
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=reza.sameer200@gmail.com
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=600s

# Logging
logging.level.com.retailmanagement=DEBUG

# SMS API DETAILS
sms.api.url=https://api.smsprovider.com/send
sms.api.key=your_sms_api_key
sms.sender.id=RetailMgmt
