BEGIN;

INSERT INTO permission (code, name, module_code)
VALUES
  ('org.view', 'View organization', 'FOUNDATION'),
  ('org.manage', 'Manage organization', 'FOUNDATION'),
  ('branch.view', 'View branches', 'FOUNDATION'),
  ('branch.manage', 'Manage branches', 'FOUNDATION'),
  ('warehouse.view', 'View warehouses', 'FOUNDATION'),
  ('warehouse.manage', 'Manage warehouses', 'FOUNDATION'),
  ('user.view', 'View users', 'USERS'),
  ('user.manage', 'Manage users', 'USERS'),
  ('subscription.view', 'View subscriptions', 'SUBSCRIPTION'),
  ('subscription.manage', 'Manage subscriptions', 'SUBSCRIPTION'),
  ('settings.view', 'View settings', 'SETTINGS'),
  ('settings.manage', 'Manage settings', 'SETTINGS'),
  ('catalog.view', 'View catalog', 'CATALOG'),
  ('catalog.manage', 'Manage catalog', 'CATALOG'),
  ('inventory.view', 'View inventory', 'INVENTORY'),
  ('inventory.receive', 'Receive inventory', 'INVENTORY'),
  ('inventory.adjust', 'Adjust inventory', 'INVENTORY'),
  ('inventory.transfer', 'Transfer inventory', 'INVENTORY'),
  ('purchase.view', 'View purchases', 'PURCHASE'),
  ('purchase.create', 'Create purchases', 'PURCHASE'),
  ('purchase.approve', 'Approve purchases', 'PURCHASE'),
  ('purchase.post', 'Post purchase documents', 'PURCHASE'),
  ('sales.view', 'View sales', 'SALES'),
  ('sales.create', 'Create sales', 'SALES'),
  ('sales.post', 'Post sales documents', 'SALES'),
  ('sales.return', 'Process sales returns', 'SALES'),
  ('payment.receive', 'Receive payments', 'PAYMENTS'),
  ('payment.pay', 'Create outgoing payments', 'PAYMENTS'),
  ('report.branch.view', 'View branch reports', 'REPORTS'),
  ('report.org.view', 'View organization reports', 'REPORTS'),
  ('tax.view', 'View tax settings', 'TAX'),
  ('tax.manage', 'Manage tax settings', 'TAX'),
  ('accounting.view', 'View accounting', 'ACCOUNTING'),
  ('accounting.post', 'Post accounting entries', 'ACCOUNTING'),
  ('service.view', 'View service', 'SERVICE'),
  ('service.manage', 'Manage service', 'SERVICE'),
  ('approval.manage', 'Manage approvals', 'APPROVALS')
ON CONFLICT (code) DO NOTHING;

WITH rp(role_code, permission_code) AS (
  VALUES
    ('OWNER','org.view'),
    ('OWNER','org.manage'),
    ('OWNER','branch.view'),
    ('OWNER','branch.manage'),
    ('OWNER','warehouse.view'),
    ('OWNER','warehouse.manage'),
    ('OWNER','user.view'),
    ('OWNER','user.manage'),
    ('OWNER','subscription.view'),
    ('OWNER','subscription.manage'),
    ('OWNER','settings.view'),
    ('OWNER','settings.manage'),
    ('OWNER','catalog.view'),
    ('OWNER','catalog.manage'),
    ('OWNER','inventory.view'),
    ('OWNER','inventory.receive'),
    ('OWNER','inventory.adjust'),
    ('OWNER','inventory.transfer'),
    ('OWNER','purchase.view'),
    ('OWNER','purchase.create'),
    ('OWNER','purchase.approve'),
    ('OWNER','purchase.post'),
    ('OWNER','sales.view'),
    ('OWNER','sales.create'),
    ('OWNER','sales.post'),
    ('OWNER','sales.return'),
    ('OWNER','payment.receive'),
    ('OWNER','payment.pay'),
    ('OWNER','report.branch.view'),
    ('OWNER','report.org.view'),
    ('OWNER','tax.view'),
    ('OWNER','tax.manage'),
    ('OWNER','accounting.view'),
    ('OWNER','accounting.post'),
    ('OWNER','service.view'),
    ('OWNER','service.manage'),
    ('OWNER','approval.manage'),

    ('ADMIN','org.view'),
    ('ADMIN','branch.view'),
    ('ADMIN','branch.manage'),
    ('ADMIN','warehouse.view'),
    ('ADMIN','warehouse.manage'),
    ('ADMIN','user.view'),
    ('ADMIN','user.manage'),
    ('ADMIN','subscription.view'),
    ('ADMIN','settings.view'),
    ('ADMIN','settings.manage'),
    ('ADMIN','catalog.view'),
    ('ADMIN','catalog.manage'),
    ('ADMIN','inventory.view'),
    ('ADMIN','inventory.receive'),
    ('ADMIN','inventory.adjust'),
    ('ADMIN','inventory.transfer'),
    ('ADMIN','purchase.view'),
    ('ADMIN','purchase.create'),
    ('ADMIN','purchase.approve'),
    ('ADMIN','purchase.post'),
    ('ADMIN','sales.view'),
    ('ADMIN','sales.create'),
    ('ADMIN','sales.post'),
    ('ADMIN','sales.return'),
    ('ADMIN','payment.receive'),
    ('ADMIN','payment.pay'),
    ('ADMIN','report.branch.view'),
    ('ADMIN','report.org.view'),
    ('ADMIN','tax.view'),
    ('ADMIN','accounting.view'),
    ('ADMIN','service.view'),
    ('ADMIN','service.manage'),
    ('ADMIN','approval.manage'),

    ('ACCOUNTANT','org.view'),
    ('ACCOUNTANT','branch.view'),
    ('ACCOUNTANT','warehouse.view'),
    ('ACCOUNTANT','catalog.view'),
    ('ACCOUNTANT','inventory.view'),
    ('ACCOUNTANT','purchase.view'),
    ('ACCOUNTANT','sales.view'),
    ('ACCOUNTANT','payment.receive'),
    ('ACCOUNTANT','payment.pay'),
    ('ACCOUNTANT','report.branch.view'),
    ('ACCOUNTANT','report.org.view'),
    ('ACCOUNTANT','tax.view'),
    ('ACCOUNTANT','tax.manage'),
    ('ACCOUNTANT','accounting.view'),
    ('ACCOUNTANT','accounting.post'),
    ('ACCOUNTANT','service.view'),

    ('STORE_MANAGER','org.view'),
    ('STORE_MANAGER','branch.view'),
    ('STORE_MANAGER','warehouse.view'),
    ('STORE_MANAGER','catalog.view'),
    ('STORE_MANAGER','catalog.manage'),
    ('STORE_MANAGER','inventory.view'),
    ('STORE_MANAGER','inventory.receive'),
    ('STORE_MANAGER','inventory.adjust'),
    ('STORE_MANAGER','inventory.transfer'),
    ('STORE_MANAGER','purchase.view'),
    ('STORE_MANAGER','purchase.create'),
    ('STORE_MANAGER','purchase.post'),
    ('STORE_MANAGER','sales.view'),
    ('STORE_MANAGER','sales.create'),
    ('STORE_MANAGER','sales.post'),
    ('STORE_MANAGER','sales.return'),
    ('STORE_MANAGER','payment.receive'),
    ('STORE_MANAGER','report.branch.view'),
    ('STORE_MANAGER','service.view'),
    ('STORE_MANAGER','service.manage'),

    ('CASHIER','branch.view'),
    ('CASHIER','warehouse.view'),
    ('CASHIER','catalog.view'),
    ('CASHIER','inventory.view'),
    ('CASHIER','sales.view'),
    ('CASHIER','sales.create'),
    ('CASHIER','sales.post'),
    ('CASHIER','sales.return'),
    ('CASHIER','payment.receive'),

    ('PURCHASE_OPERATOR','branch.view'),
    ('PURCHASE_OPERATOR','warehouse.view'),
    ('PURCHASE_OPERATOR','catalog.view'),
    ('PURCHASE_OPERATOR','inventory.view'),
    ('PURCHASE_OPERATOR','inventory.receive'),
    ('PURCHASE_OPERATOR','purchase.view'),
    ('PURCHASE_OPERATOR','purchase.create'),
    ('PURCHASE_OPERATOR','purchase.post'),

    ('TECHNICIAN','branch.view'),
    ('TECHNICIAN','catalog.view'),
    ('TECHNICIAN','inventory.view'),
    ('TECHNICIAN','service.view'),
    ('TECHNICIAN','service.manage'),

    ('VIEWER','org.view'),
    ('VIEWER','branch.view'),
    ('VIEWER','warehouse.view'),
    ('VIEWER','catalog.view'),
    ('VIEWER','inventory.view'),
    ('VIEWER','purchase.view'),
    ('VIEWER','sales.view'),
    ('VIEWER','report.branch.view'),
    ('VIEWER','service.view')
)
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM rp
JOIN role r ON r.code = rp.role_code
JOIN permission p ON p.code = rp.permission_code
ON CONFLICT (role_id, permission_id) DO NOTHING;

COMMIT;
