-- liquibase formatted sql

-- changeset sameer:post-bootstrap-001-add-report-storage
CREATE TABLE IF NOT EXISTS "reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "report_id" VARCHAR(255) NOT NULL,
  "report_name" VARCHAR(255) NOT NULL,
  "report_type" VARCHAR(255),
  "format" VARCHAR(255),
  "generated_by" BIGINT,
  "generated_date" TIMESTAMP WITH TIME ZONE,
  "start_date" TIMESTAMP WITH TIME ZONE,
  "end_date" TIMESTAMP WITH TIME ZONE,
  "description" VARCHAR(1000),
  "file_path" VARCHAR(255),
  "file_url" VARCHAR(255),
  "file_size" BIGINT,
  "is_scheduled" BOOLEAN DEFAULT FALSE NOT NULL,
  "schedule_cron" VARCHAR(255),
  "next_scheduled_date" TIMESTAMP WITH TIME ZONE,
  "recipients" VARCHAR(255),
  "download_count" INTEGER DEFAULT 0 NOT NULL,
  "status" VARCHAR(50),
  "error_message" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CONSTRAINT "reports_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_reports_report_id" UNIQUE ("report_id"),
  CONSTRAINT "fk_reports_generated_by" FOREIGN KEY ("generated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "report_parameters" (
  "report_id" BIGINT NOT NULL,
  "param_key" VARCHAR(255) NOT NULL,
  "param_value" VARCHAR(500),
  CONSTRAINT "report_parameters_pkey" PRIMARY KEY ("report_id", "param_key"),
  CONSTRAINT "fk_report_parameters_report" FOREIGN KEY ("report_id") REFERENCES "reports" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_reports_generated_by" ON "reports" ("generated_by");
CREATE INDEX IF NOT EXISTS "idx_reports_generated_date" ON "reports" ("generated_date");
