-- liquibase formatted sql

-- changeset sameer:post-bootstrap-002-add-governance-incidents-and-stock-count
ALTER TABLE "product"
  ADD COLUMN IF NOT EXISTS "governance_status" VARCHAR(30) DEFAULT 'ACTIVE' NOT NULL,
  ADD COLUMN IF NOT EXISTS "quality_review_status" VARCHAR(30) DEFAULT 'NORMAL' NOT NULL,
  ADD COLUMN IF NOT EXISTS "block_new_store_adoption" BOOLEAN DEFAULT FALSE NOT NULL,
  ADD COLUMN IF NOT EXISTS "block_transactions" BOOLEAN DEFAULT FALSE NOT NULL,
  ADD COLUMN IF NOT EXISTS "governance_reason" TEXT,
  ADD COLUMN IF NOT EXISTS "governance_updated_at" TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS "platform_incident" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "incident_number" VARCHAR(80) NOT NULL,
  "organization_id" BIGINT,
  "subject_type" VARCHAR(30) NOT NULL,
  "incident_type" VARCHAR(40) NOT NULL,
  "severity" VARCHAR(20) NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  "description" TEXT,
  "product_id" BIGINT,
  "store_product_id" BIGINT,
  "service_ticket_id" BIGINT,
  "warranty_claim_id" BIGINT,
  "reported_by" VARCHAR(150),
  "recommended_action" VARCHAR(60),
  "action_taken" VARCHAR(60),
  "resolution_notes" TEXT,
  "opened_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "resolved_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "platform_incident_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_platform_incident_number" UNIQUE ("incident_number")
);

CREATE TABLE IF NOT EXISTS "stock_count_session" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "warehouse_id" BIGINT NOT NULL,
  "count_number" VARCHAR(80) NOT NULL,
  "count_date" DATE NOT NULL,
  "status" VARCHAR(30) NOT NULL,
  "notes" TEXT,
  "started_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "submitted_at" TIMESTAMP WITH TIME ZONE,
  "variance_posted_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "stock_count_session_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_stock_count_session_number" UNIQUE ("count_number")
);

CREATE TABLE IF NOT EXISTS "stock_count_line" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stock_count_session_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "batch_id" BIGINT,
  "expected_base_quantity" NUMERIC(18,6) NOT NULL,
  "counted_base_quantity" NUMERIC(18,6) NOT NULL,
  "variance_base_quantity" NUMERIC(18,6) NOT NULL,
  "posted_adjustment_id" BIGINT,
  "remarks" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "stock_count_line_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_stock_count_line_scope" UNIQUE ("stock_count_session_id", "product_id", "batch_id")
);

CREATE INDEX IF NOT EXISTS "idx_product_governance_status" ON "product" ("governance_status");
CREATE INDEX IF NOT EXISTS "idx_platform_incident_status" ON "platform_incident" ("status", "opened_at");
CREATE INDEX IF NOT EXISTS "idx_platform_incident_product" ON "platform_incident" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_platform_incident_org" ON "platform_incident" ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_stock_count_session_org" ON "stock_count_session" ("organization_id", "warehouse_id", "count_date");
CREATE INDEX IF NOT EXISTS "idx_stock_count_line_session" ON "stock_count_line" ("stock_count_session_id");

ALTER TABLE "platform_incident"
  ADD CONSTRAINT "platform_incident_organization_id_fkey"
    FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "platform_incident"
  ADD CONSTRAINT "platform_incident_product_id_fkey"
    FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "platform_incident"
  ADD CONSTRAINT "platform_incident_store_product_id_fkey"
    FOREIGN KEY ("store_product_id") REFERENCES "store_product" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "platform_incident"
  ADD CONSTRAINT "platform_incident_service_ticket_id_fkey"
    FOREIGN KEY ("service_ticket_id") REFERENCES "service_ticket" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "platform_incident"
  ADD CONSTRAINT "platform_incident_warranty_claim_id_fkey"
    FOREIGN KEY ("warranty_claim_id") REFERENCES "warranty_claim" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "platform_incident"
  ADD CONSTRAINT "platform_incident_created_by_fkey"
    FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "platform_incident"
  ADD CONSTRAINT "platform_incident_updated_by_fkey"
    FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "stock_count_session"
  ADD CONSTRAINT "stock_count_session_organization_id_fkey"
    FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "stock_count_session"
  ADD CONSTRAINT "stock_count_session_branch_id_fkey"
    FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "stock_count_session"
  ADD CONSTRAINT "stock_count_session_warehouse_id_fkey"
    FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "stock_count_session"
  ADD CONSTRAINT "stock_count_session_created_by_fkey"
    FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "stock_count_session"
  ADD CONSTRAINT "stock_count_session_updated_by_fkey"
    FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "stock_count_line"
  ADD CONSTRAINT "stock_count_line_session_id_fkey"
    FOREIGN KEY ("stock_count_session_id") REFERENCES "stock_count_session" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "stock_count_line"
  ADD CONSTRAINT "stock_count_line_product_id_fkey"
    FOREIGN KEY ("product_id") REFERENCES "store_product" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "stock_count_line"
  ADD CONSTRAINT "stock_count_line_batch_id_fkey"
    FOREIGN KEY ("batch_id") REFERENCES "inventory_batch" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "stock_count_line"
  ADD CONSTRAINT "stock_count_line_posted_adjustment_id_fkey"
    FOREIGN KEY ("posted_adjustment_id") REFERENCES "stock_adjustment" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "stock_count_line"
  ADD CONSTRAINT "stock_count_line_created_by_fkey"
    FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "stock_count_line"
  ADD CONSTRAINT "stock_count_line_updated_by_fkey"
    FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
