CREATE TABLE IF NOT EXISTS "tax_compliance_document" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "organization_id" BIGINT NOT NULL,
    "branch_id" BIGINT NOT NULL,
    "source_type" VARCHAR(40) NOT NULL,
    "source_id" BIGINT NOT NULL,
    "document_type" VARCHAR(40) NOT NULL,
    "provider_code" VARCHAR(40) NOT NULL,
    "status" VARCHAR(30) NOT NULL,
    "eligible_for_submission" BOOLEAN DEFAULT FALSE NOT NULL,
    "payload_json" TEXT,
    "response_json" TEXT,
    "warning_json" TEXT,
    "external_reference" VARCHAR(120),
    "acknowledgement_number" VARCHAR(120),
    "acknowledgement_date_time" TIMESTAMP WITH TIME ZONE,
    "generated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "error_message" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "created_by" BIGINT,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_by" BIGINT,
    CONSTRAINT "tax_compliance_document_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_tax_compliance_source"
    ON "tax_compliance_document" ("organization_id", "source_type", "source_id");

CREATE INDEX IF NOT EXISTS "idx_tax_compliance_type"
    ON "tax_compliance_document" ("organization_id", "document_type", "status");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_tax_compliance_document_created_by'
    ) THEN
        ALTER TABLE "tax_compliance_document"
            ADD CONSTRAINT "fk_tax_compliance_document_created_by"
            FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_tax_compliance_document_updated_by'
    ) THEN
        ALTER TABLE "tax_compliance_document"
            ADD CONSTRAINT "fk_tax_compliance_document_updated_by"
            FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tax_compliance_document_branch_id_fkey'
    ) THEN
        ALTER TABLE "tax_compliance_document"
            ADD CONSTRAINT "tax_compliance_document_branch_id_fkey"
            FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'tax_compliance_document_organization_id_fkey'
    ) THEN
        ALTER TABLE "tax_compliance_document"
            ADD CONSTRAINT "tax_compliance_document_organization_id_fkey"
            FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
    END IF;
END $$;
