-- liquibase formatted sql

-- changeset sameer:post-bootstrap-008-add-sales-dispatch-foundation
CREATE TABLE IF NOT EXISTS "sales_dispatch" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "sales_invoice_id" BIGINT NOT NULL,
  "warehouse_id" BIGINT NOT NULL,
  "customer_id" BIGINT NOT NULL,
  "dispatch_number" VARCHAR(80) NOT NULL,
  "dispatch_date" DATE NOT NULL,
  "expected_delivery_date" DATE,
  "status" VARCHAR(30) NOT NULL,
  "transporter_name" VARCHAR(200),
  "transporter_id" VARCHAR(80),
  "vehicle_number" VARCHAR(60),
  "tracking_number" VARCHAR(120),
  "delivery_address" TEXT,
  "remarks" TEXT,
  "packed_at" TIMESTAMP WITH TIME ZONE,
  "dispatched_at" TIMESTAMP WITH TIME ZONE,
  "delivered_at" TIMESTAMP WITH TIME ZONE,
  "cancelled_at" TIMESTAMP WITH TIME ZONE,
  "cancel_reason" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "sales_dispatch_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_sales_dispatch_number" UNIQUE ("dispatch_number")
);

CREATE TABLE IF NOT EXISTS "sales_dispatch_line" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sales_dispatch_id" BIGINT NOT NULL,
  "sales_invoice_line_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "uom_id" BIGINT NOT NULL,
  "quantity" NUMERIC(18,6) NOT NULL,
  "base_quantity" NUMERIC(18,6) NOT NULL,
  "remarks" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "sales_dispatch_line_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_sales_dispatch_org" ON "sales_dispatch" ("organization_id", "dispatch_date");
CREATE INDEX IF NOT EXISTS "idx_sales_dispatch_invoice" ON "sales_dispatch" ("sales_invoice_id", "status");
CREATE INDEX IF NOT EXISTS "idx_sales_dispatch_line_dispatch" ON "sales_dispatch_line" ("sales_dispatch_id");
CREATE INDEX IF NOT EXISTS "idx_sales_dispatch_line_invoice_line" ON "sales_dispatch_line" ("sales_invoice_line_id");

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_organization_id_fkey') THEN
    ALTER TABLE "sales_dispatch"
      ADD CONSTRAINT "sales_dispatch_organization_id_fkey"
      FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_branch_id_fkey') THEN
    ALTER TABLE "sales_dispatch"
      ADD CONSTRAINT "sales_dispatch_branch_id_fkey"
      FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_invoice_id_fkey') THEN
    ALTER TABLE "sales_dispatch"
      ADD CONSTRAINT "sales_dispatch_invoice_id_fkey"
      FOREIGN KEY ("sales_invoice_id") REFERENCES "sales_invoice" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_warehouse_id_fkey') THEN
    ALTER TABLE "sales_dispatch"
      ADD CONSTRAINT "sales_dispatch_warehouse_id_fkey"
      FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_customer_id_fkey') THEN
    ALTER TABLE "sales_dispatch"
      ADD CONSTRAINT "sales_dispatch_customer_id_fkey"
      FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_created_by_fkey') THEN
    ALTER TABLE "sales_dispatch"
      ADD CONSTRAINT "sales_dispatch_created_by_fkey"
      FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_updated_by_fkey') THEN
    ALTER TABLE "sales_dispatch"
      ADD CONSTRAINT "sales_dispatch_updated_by_fkey"
      FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_line_dispatch_id_fkey') THEN
    ALTER TABLE "sales_dispatch_line"
      ADD CONSTRAINT "sales_dispatch_line_dispatch_id_fkey"
      FOREIGN KEY ("sales_dispatch_id") REFERENCES "sales_dispatch" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_line_invoice_line_id_fkey') THEN
    ALTER TABLE "sales_dispatch_line"
      ADD CONSTRAINT "sales_dispatch_line_invoice_line_id_fkey"
      FOREIGN KEY ("sales_invoice_line_id") REFERENCES "sales_invoice_line" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_line_product_id_fkey') THEN
    ALTER TABLE "sales_dispatch_line"
      ADD CONSTRAINT "sales_dispatch_line_product_id_fkey"
      FOREIGN KEY ("product_id") REFERENCES "store_product" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_line_uom_id_fkey') THEN
    ALTER TABLE "sales_dispatch_line"
      ADD CONSTRAINT "sales_dispatch_line_uom_id_fkey"
      FOREIGN KEY ("uom_id") REFERENCES "uom" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_line_created_by_fkey') THEN
    ALTER TABLE "sales_dispatch_line"
      ADD CONSTRAINT "sales_dispatch_line_created_by_fkey"
      FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sales_dispatch_line_updated_by_fkey') THEN
    ALTER TABLE "sales_dispatch_line"
      ADD CONSTRAINT "sales_dispatch_line_updated_by_fkey"
      FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;
