CREATE TABLE IF NOT EXISTS "sales_invoice_payment_request" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "sales_invoice_id" BIGINT NOT NULL,
  "customer_id" BIGINT NOT NULL,
  "request_number" VARCHAR(80) NOT NULL,
  "request_date" DATE NOT NULL,
  "due_date" DATE,
  "expires_on" DATE,
  "requested_amount" NUMERIC(18, 2) NOT NULL,
  "provider_code" VARCHAR(40) NOT NULL DEFAULT 'MANUAL',
  "channel" VARCHAR(30) NOT NULL DEFAULT 'LINK',
  "payment_link_token" VARCHAR(120) NOT NULL,
  "payment_link_url" VARCHAR(255),
  "status" VARCHAR(30) NOT NULL,
  "last_sent_at" TIMESTAMP WITH TIME ZONE,
  "remarks" TEXT,
  "cancelled_at" TIMESTAMP WITH TIME ZONE,
  "cancelled_by" BIGINT,
  "cancel_reason" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "sales_invoice_payment_request_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_sales_invoice_payment_request_number" UNIQUE ("request_number"),
  CONSTRAINT "uq_sales_invoice_payment_request_token" UNIQUE ("payment_link_token")
);

CREATE TABLE IF NOT EXISTS "bank_statement_import_batch" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "account_id" BIGINT NOT NULL,
  "import_reference" VARCHAR(80) NOT NULL,
  "source_type" VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
  "source_reference" VARCHAR(120),
  "source_file_name" VARCHAR(255),
  "statement_from_date" DATE,
  "statement_to_date" DATE,
  "entry_count" INTEGER NOT NULL DEFAULT 0,
  "total_debit_amount" NUMERIC(18, 2) NOT NULL DEFAULT 0,
  "total_credit_amount" NUMERIC(18, 2) NOT NULL DEFAULT 0,
  "status" VARCHAR(30) NOT NULL DEFAULT 'IMPORTED',
  "imported_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "imported_by" BIGINT,
  "remarks" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "bank_statement_import_batch_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_bank_statement_import_batch_reference" UNIQUE ("import_reference")
);

ALTER TABLE "bank_statement_entry"
  ADD COLUMN IF NOT EXISTS "import_batch_id" BIGINT;

CREATE INDEX IF NOT EXISTS "idx_sales_invoice_payment_request_invoice"
  ON "sales_invoice_payment_request" ("sales_invoice_id", "status");

CREATE INDEX IF NOT EXISTS "idx_sales_invoice_payment_request_org"
  ON "sales_invoice_payment_request" ("organization_id", "request_date");

CREATE INDEX IF NOT EXISTS "idx_bank_statement_import_batch_org_account"
  ON "bank_statement_import_batch" ("organization_id", "account_id", "imported_at");

CREATE INDEX IF NOT EXISTS "idx_bank_statement_entry_import_batch"
  ON "bank_statement_entry" ("import_batch_id", "entry_date");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_payment_request_org_fkey'
      AND table_name = 'sales_invoice_payment_request'
  ) THEN
    ALTER TABLE "sales_invoice_payment_request"
      ADD CONSTRAINT "sales_invoice_payment_request_org_fkey"
      FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_payment_request_branch_fkey'
      AND table_name = 'sales_invoice_payment_request'
  ) THEN
    ALTER TABLE "sales_invoice_payment_request"
      ADD CONSTRAINT "sales_invoice_payment_request_branch_fkey"
      FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_payment_request_invoice_fkey'
      AND table_name = 'sales_invoice_payment_request'
  ) THEN
    ALTER TABLE "sales_invoice_payment_request"
      ADD CONSTRAINT "sales_invoice_payment_request_invoice_fkey"
      FOREIGN KEY ("sales_invoice_id") REFERENCES "sales_invoice" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_payment_request_customer_fkey'
      AND table_name = 'sales_invoice_payment_request'
  ) THEN
    ALTER TABLE "sales_invoice_payment_request"
      ADD CONSTRAINT "sales_invoice_payment_request_customer_fkey"
      FOREIGN KEY ("customer_id") REFERENCES "customer" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_payment_request_cancelled_by_fkey'
      AND table_name = 'sales_invoice_payment_request'
  ) THEN
    ALTER TABLE "sales_invoice_payment_request"
      ADD CONSTRAINT "sales_invoice_payment_request_cancelled_by_fkey"
      FOREIGN KEY ("cancelled_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_payment_request_created_by_fkey'
      AND table_name = 'sales_invoice_payment_request'
  ) THEN
    ALTER TABLE "sales_invoice_payment_request"
      ADD CONSTRAINT "sales_invoice_payment_request_created_by_fkey"
      FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_payment_request_updated_by_fkey'
      AND table_name = 'sales_invoice_payment_request'
  ) THEN
    ALTER TABLE "sales_invoice_payment_request"
      ADD CONSTRAINT "sales_invoice_payment_request_updated_by_fkey"
      FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'bank_statement_import_batch_org_fkey'
      AND table_name = 'bank_statement_import_batch'
  ) THEN
    ALTER TABLE "bank_statement_import_batch"
      ADD CONSTRAINT "bank_statement_import_batch_org_fkey"
      FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'bank_statement_import_batch_branch_fkey'
      AND table_name = 'bank_statement_import_batch'
  ) THEN
    ALTER TABLE "bank_statement_import_batch"
      ADD CONSTRAINT "bank_statement_import_batch_branch_fkey"
      FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'bank_statement_import_batch_account_fkey'
      AND table_name = 'bank_statement_import_batch'
  ) THEN
    ALTER TABLE "bank_statement_import_batch"
      ADD CONSTRAINT "bank_statement_import_batch_account_fkey"
      FOREIGN KEY ("account_id") REFERENCES "account" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'bank_statement_import_batch_imported_by_fkey'
      AND table_name = 'bank_statement_import_batch'
  ) THEN
    ALTER TABLE "bank_statement_import_batch"
      ADD CONSTRAINT "bank_statement_import_batch_imported_by_fkey"
      FOREIGN KEY ("imported_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'bank_statement_import_batch_created_by_fkey'
      AND table_name = 'bank_statement_import_batch'
  ) THEN
    ALTER TABLE "bank_statement_import_batch"
      ADD CONSTRAINT "bank_statement_import_batch_created_by_fkey"
      FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'bank_statement_import_batch_updated_by_fkey'
      AND table_name = 'bank_statement_import_batch'
  ) THEN
    ALTER TABLE "bank_statement_import_batch"
      ADD CONSTRAINT "bank_statement_import_batch_updated_by_fkey"
      FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'bank_statement_entry_import_batch_fkey'
      AND table_name = 'bank_statement_entry'
  ) THEN
    ALTER TABLE "bank_statement_entry"
      ADD CONSTRAINT "bank_statement_entry_import_batch_fkey"
      FOREIGN KEY ("import_batch_id") REFERENCES "bank_statement_import_batch" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;
