CREATE TABLE IF NOT EXISTS "import_job" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT,
  "entity_type" VARCHAR(40) NOT NULL,
  "source_file_name" VARCHAR(255),
  "content_type" VARCHAR(120),
  "update_existing" BOOLEAN NOT NULL DEFAULT FALSE,
  "total_rows" INTEGER NOT NULL DEFAULT 0,
  "valid_rows" INTEGER NOT NULL DEFAULT 0,
  "imported_rows" INTEGER NOT NULL DEFAULT 0,
  "failed_rows" INTEGER NOT NULL DEFAULT 0,
  "status" VARCHAR(30) NOT NULL,
  "started_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "completed_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "import_job_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "import_job_row" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "import_job_id" BIGINT NOT NULL,
  "row_number" INTEGER NOT NULL,
  "action" VARCHAR(20) NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "reference" VARCHAR(255),
  "messages_json" TEXT,
  "values_json" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "import_job_row_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_import_job_org_entity" ON "import_job" ("organization_id", "entity_type", "started_at");
CREATE INDEX IF NOT EXISTS "idx_import_job_org_status" ON "import_job" ("organization_id", "status", "started_at");
CREATE INDEX IF NOT EXISTS "idx_import_job_row_job" ON "import_job_row" ("import_job_id", "row_number");
CREATE INDEX IF NOT EXISTS "idx_import_job_row_job_status" ON "import_job_row" ("import_job_id", "status");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'import_job_org_fkey' AND table_name = 'import_job'
  ) THEN
    ALTER TABLE "import_job"
      ADD CONSTRAINT "import_job_org_fkey"
      FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'import_job_branch_fkey' AND table_name = 'import_job'
  ) THEN
    ALTER TABLE "import_job"
      ADD CONSTRAINT "import_job_branch_fkey"
      FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'import_job_created_by_fkey' AND table_name = 'import_job'
  ) THEN
    ALTER TABLE "import_job"
      ADD CONSTRAINT "import_job_created_by_fkey"
      FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'import_job_updated_by_fkey' AND table_name = 'import_job'
  ) THEN
    ALTER TABLE "import_job"
      ADD CONSTRAINT "import_job_updated_by_fkey"
      FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'import_job_row_job_fkey' AND table_name = 'import_job_row'
  ) THEN
    ALTER TABLE "import_job_row"
      ADD CONSTRAINT "import_job_row_job_fkey"
      FOREIGN KEY ("import_job_id") REFERENCES "import_job" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'import_job_row_created_by_fkey' AND table_name = 'import_job_row'
  ) THEN
    ALTER TABLE "import_job_row"
      ADD CONSTRAINT "import_job_row_created_by_fkey"
      FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'import_job_row_updated_by_fkey' AND table_name = 'import_job_row'
  ) THEN
    ALTER TABLE "import_job_row"
      ADD CONSTRAINT "import_job_row_updated_by_fkey"
      FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;
