CREATE TABLE IF NOT EXISTS "pos_session" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "warehouse_id" BIGINT NOT NULL,
  "session_number" VARCHAR(80) NOT NULL,
  "terminal_name" VARCHAR(120),
  "opened_by_user_id" BIGINT NOT NULL,
  "opened_by_username" VARCHAR(150) NOT NULL,
  "opened_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "opening_cash_amount" numeric(18, 2) DEFAULT 0 NOT NULL,
  "opening_notes" TEXT,
  "status" VARCHAR(20) NOT NULL,
  "closed_by_user_id" BIGINT,
  "closed_by_username" VARCHAR(150),
  "closed_at" TIMESTAMP WITH TIME ZONE,
  "expected_closing_cash_amount" numeric(18, 2),
  "counted_closing_cash_amount" numeric(18, 2),
  "cash_variance_amount" numeric(18, 2),
  "closing_notes" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "pos_session_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "sales_invoice"
  ADD COLUMN IF NOT EXISTS "pos_session_id" BIGINT;

ALTER TABLE "customer_receipt"
  ADD COLUMN IF NOT EXISTS "pos_session_id" BIGINT;

CREATE INDEX IF NOT EXISTS "idx_pos_session_org_branch_status"
  ON "pos_session" ("organization_id", "branch_id", "status", "opened_at");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_pos_session_org_number"
  ON "pos_session" ("organization_id", "session_number");
CREATE INDEX IF NOT EXISTS "idx_sales_invoice_pos_session"
  ON "sales_invoice" ("organization_id", "pos_session_id", "invoice_date");
CREATE INDEX IF NOT EXISTS "idx_customer_receipt_pos_session"
  ON "customer_receipt" ("organization_id", "pos_session_id", "receipt_date");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'pos_session_branch_id_fkey' AND table_name = 'pos_session'
  ) THEN
    ALTER TABLE "pos_session"
      ADD CONSTRAINT "pos_session_branch_id_fkey"
      FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'pos_session_organization_id_fkey' AND table_name = 'pos_session'
  ) THEN
    ALTER TABLE "pos_session"
      ADD CONSTRAINT "pos_session_organization_id_fkey"
      FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'pos_session_warehouse_id_fkey' AND table_name = 'pos_session'
  ) THEN
    ALTER TABLE "pos_session"
      ADD CONSTRAINT "pos_session_warehouse_id_fkey"
      FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'pos_session_opened_by_user_id_fkey' AND table_name = 'pos_session'
  ) THEN
    ALTER TABLE "pos_session"
      ADD CONSTRAINT "pos_session_opened_by_user_id_fkey"
      FOREIGN KEY ("opened_by_user_id") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'pos_session_closed_by_user_id_fkey' AND table_name = 'pos_session'
  ) THEN
    ALTER TABLE "pos_session"
      ADD CONSTRAINT "pos_session_closed_by_user_id_fkey"
      FOREIGN KEY ("closed_by_user_id") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_pos_session_created_by' AND table_name = 'pos_session'
  ) THEN
    ALTER TABLE "pos_session"
      ADD CONSTRAINT "fk_pos_session_created_by"
      FOREIGN KEY ("created_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_pos_session_updated_by' AND table_name = 'pos_session'
  ) THEN
    ALTER TABLE "pos_session"
      ADD CONSTRAINT "fk_pos_session_updated_by"
      FOREIGN KEY ("updated_by") REFERENCES "app_user" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_invoice_pos_session_id_fkey' AND table_name = 'sales_invoice'
  ) THEN
    ALTER TABLE "sales_invoice"
      ADD CONSTRAINT "sales_invoice_pos_session_id_fkey"
      FOREIGN KEY ("pos_session_id") REFERENCES "pos_session" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'customer_receipt_pos_session_id_fkey' AND table_name = 'customer_receipt'
  ) THEN
    ALTER TABLE "customer_receipt"
      ADD CONSTRAINT "customer_receipt_pos_session_id_fkey"
      FOREIGN KEY ("pos_session_id") REFERENCES "pos_session" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;
