CREATE TABLE IF NOT EXISTS "purchase_order_supplier_access" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "purchase_order_id" BIGINT NOT NULL,
  "supplier_id" BIGINT NOT NULL,
  "access_token" VARCHAR(120) NOT NULL,
  "expires_on" DATE NOT NULL,
  "last_accessed_at" TIMESTAMP WITH TIME ZONE,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "purchase_order_supplier_access_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_purchase_order_supplier_access_token" UNIQUE ("access_token"),
  CONSTRAINT "uq_purchase_order_supplier_access_order" UNIQUE ("purchase_order_id")
);

CREATE TABLE IF NOT EXISTS "purchase_order_supplier_dispatch_notice" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "branch_id" BIGINT NOT NULL,
  "purchase_order_id" BIGINT NOT NULL,
  "supplier_id" BIGINT NOT NULL,
  "dispatch_number" VARCHAR(80) NOT NULL,
  "dispatch_date" DATE NOT NULL,
  "expected_delivery_date" DATE,
  "supplier_reference_number" VARCHAR(120),
  "transporter_name" VARCHAR(120),
  "vehicle_number" VARCHAR(60),
  "tracking_number" VARCHAR(120),
  "status" VARCHAR(30) NOT NULL,
  "remarks" TEXT,
  "submitted_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "purchase_order_supplier_dispatch_notice_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_purchase_order_supplier_dispatch_number" UNIQUE ("dispatch_number")
);

CREATE TABLE IF NOT EXISTS "purchase_order_supplier_dispatch_notice_line" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dispatch_notice_id" BIGINT NOT NULL,
  "purchase_order_line_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "ordered_quantity_snapshot" NUMERIC(18, 6) NOT NULL,
  "ordered_base_quantity_snapshot" NUMERIC(18, 6) NOT NULL,
  "dispatched_quantity" NUMERIC(18, 6) NOT NULL,
  "dispatched_base_quantity" NUMERIC(18, 6) NOT NULL,
  "expected_remaining_dispatch_on" DATE,
  "remarks" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "created_by" BIGINT,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_by" BIGINT,
  CONSTRAINT "purchase_order_supplier_dispatch_notice_line_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_purchase_order_supplier_access_order"
  ON "purchase_order_supplier_access" ("purchase_order_id");
CREATE INDEX IF NOT EXISTS "idx_purchase_order_supplier_access_token"
  ON "purchase_order_supplier_access" ("access_token");
CREATE INDEX IF NOT EXISTS "idx_po_supplier_dispatch_order"
  ON "purchase_order_supplier_dispatch_notice" ("purchase_order_id", "dispatch_date");
CREATE INDEX IF NOT EXISTS "idx_po_supplier_dispatch_supplier"
  ON "purchase_order_supplier_dispatch_notice" ("supplier_id", "dispatch_date");
CREATE INDEX IF NOT EXISTS "idx_po_supplier_dispatch_line_notice"
  ON "purchase_order_supplier_dispatch_notice_line" ("dispatch_notice_id");
CREATE INDEX IF NOT EXISTS "idx_po_supplier_dispatch_line_order_line"
  ON "purchase_order_supplier_dispatch_notice_line" ("purchase_order_line_id");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_access_org_fkey'
      AND table_name = 'purchase_order_supplier_access'
  ) THEN
    ALTER TABLE "purchase_order_supplier_access"
      ADD CONSTRAINT "purchase_order_supplier_access_org_fkey"
      FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_access_branch_fkey'
      AND table_name = 'purchase_order_supplier_access'
  ) THEN
    ALTER TABLE "purchase_order_supplier_access"
      ADD CONSTRAINT "purchase_order_supplier_access_branch_fkey"
      FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_access_order_fkey'
      AND table_name = 'purchase_order_supplier_access'
  ) THEN
    ALTER TABLE "purchase_order_supplier_access"
      ADD CONSTRAINT "purchase_order_supplier_access_order_fkey"
      FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_order" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_access_supplier_fkey'
      AND table_name = 'purchase_order_supplier_access'
  ) THEN
    ALTER TABLE "purchase_order_supplier_access"
      ADD CONSTRAINT "purchase_order_supplier_access_supplier_fkey"
      FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_dispatch_notice_org_fkey'
      AND table_name = 'purchase_order_supplier_dispatch_notice'
  ) THEN
    ALTER TABLE "purchase_order_supplier_dispatch_notice"
      ADD CONSTRAINT "purchase_order_supplier_dispatch_notice_org_fkey"
      FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_dispatch_notice_branch_fkey'
      AND table_name = 'purchase_order_supplier_dispatch_notice'
  ) THEN
    ALTER TABLE "purchase_order_supplier_dispatch_notice"
      ADD CONSTRAINT "purchase_order_supplier_dispatch_notice_branch_fkey"
      FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_dispatch_notice_order_fkey'
      AND table_name = 'purchase_order_supplier_dispatch_notice'
  ) THEN
    ALTER TABLE "purchase_order_supplier_dispatch_notice"
      ADD CONSTRAINT "purchase_order_supplier_dispatch_notice_order_fkey"
      FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_order" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_dispatch_notice_supplier_fkey'
      AND table_name = 'purchase_order_supplier_dispatch_notice'
  ) THEN
    ALTER TABLE "purchase_order_supplier_dispatch_notice"
      ADD CONSTRAINT "purchase_order_supplier_dispatch_notice_supplier_fkey"
      FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_dispatch_notice_line_notice_fkey'
      AND table_name = 'purchase_order_supplier_dispatch_notice_line'
  ) THEN
    ALTER TABLE "purchase_order_supplier_dispatch_notice_line"
      ADD CONSTRAINT "purchase_order_supplier_dispatch_notice_line_notice_fkey"
      FOREIGN KEY ("dispatch_notice_id") REFERENCES "purchase_order_supplier_dispatch_notice" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_dispatch_notice_line_order_line_fkey'
      AND table_name = 'purchase_order_supplier_dispatch_notice_line'
  ) THEN
    ALTER TABLE "purchase_order_supplier_dispatch_notice_line"
      ADD CONSTRAINT "purchase_order_supplier_dispatch_notice_line_order_line_fkey"
      FOREIGN KEY ("purchase_order_line_id") REFERENCES "purchase_order_line" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'purchase_order_supplier_dispatch_notice_line_product_fkey'
      AND table_name = 'purchase_order_supplier_dispatch_notice_line'
  ) THEN
    ALTER TABLE "purchase_order_supplier_dispatch_notice_line"
      ADD CONSTRAINT "purchase_order_supplier_dispatch_notice_line_product_fkey"
      FOREIGN KEY ("product_id") REFERENCES "store_product" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
  END IF;
END $$;
