CREATE TABLE IF NOT EXISTS warehouse_bin_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    branch_id BIGINT,
    warehouse_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    zone_code VARCHAR(80),
    sort_order INTEGER,
    is_default BOOLEAN DEFAULT FALSE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by BIGINT,
    CONSTRAINT uq_warehouse_bin_location_org_wh_code UNIQUE (organization_id, warehouse_id, code)
);

CREATE INDEX IF NOT EXISTS idx_warehouse_bin_location_org_wh_active
    ON warehouse_bin_location (organization_id, warehouse_id, is_active);

ALTER TABLE inventory_balance
    ADD COLUMN IF NOT EXISTS bin_location_id BIGINT;

ALTER TABLE stock_movement
    ADD COLUMN IF NOT EXISTS bin_location_id BIGINT;

ALTER TABLE stock_adjustment_line
    ADD COLUMN IF NOT EXISTS bin_location_id BIGINT;

ALTER TABLE stock_transfer_line
    ADD COLUMN IF NOT EXISTS from_bin_location_id BIGINT;

ALTER TABLE stock_transfer_line
    ADD COLUMN IF NOT EXISTS to_bin_location_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_inventory_balance_bin
    ON inventory_balance (organization_id, bin_location_id, product_id);

CREATE INDEX IF NOT EXISTS idx_stock_movement_bin
    ON stock_movement (organization_id, bin_location_id, movement_at DESC);

ALTER TABLE warehouse_bin_location
    ADD CONSTRAINT warehouse_bin_location_org_fkey
    FOREIGN KEY (organization_id) REFERENCES organization (id)
    ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE warehouse_bin_location
    ADD CONSTRAINT warehouse_bin_location_branch_fkey
    FOREIGN KEY (branch_id) REFERENCES branch (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE warehouse_bin_location
    ADD CONSTRAINT warehouse_bin_location_warehouse_fkey
    FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)
    ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE warehouse_bin_location
    ADD CONSTRAINT warehouse_bin_location_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES app_user (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE warehouse_bin_location
    ADD CONSTRAINT warehouse_bin_location_updated_by_fkey
    FOREIGN KEY (updated_by) REFERENCES app_user (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE inventory_balance
    ADD CONSTRAINT inventory_balance_bin_location_fkey
    FOREIGN KEY (bin_location_id) REFERENCES warehouse_bin_location (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE stock_movement
    ADD CONSTRAINT stock_movement_bin_location_fkey
    FOREIGN KEY (bin_location_id) REFERENCES warehouse_bin_location (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE stock_adjustment_line
    ADD CONSTRAINT stock_adjustment_line_bin_location_fkey
    FOREIGN KEY (bin_location_id) REFERENCES warehouse_bin_location (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE stock_transfer_line
    ADD CONSTRAINT stock_transfer_line_from_bin_location_fkey
    FOREIGN KEY (from_bin_location_id) REFERENCES warehouse_bin_location (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE stock_transfer_line
    ADD CONSTRAINT stock_transfer_line_to_bin_location_fkey
    FOREIGN KEY (to_bin_location_id) REFERENCES warehouse_bin_location (id)
    ON UPDATE NO ACTION ON DELETE SET NULL;
