-- liquibase formatted sql

-- changeset sameerkhan:create_notification_templates_table
CREATE TABLE IF NOT EXISTS "notification_templates" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "template_code" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255),
    "type" VARCHAR(50),
    "channel" VARCHAR(50),
    "subject" VARCHAR(255) NOT NULL,
    "content" VARCHAR(5000),
    "content_html" TEXT,
    "sms_content" TEXT,
    "push_title" VARCHAR(255),
    "push_content" TEXT,
    "placeholders" VARCHAR(1000),
    "is_active" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_by" VARCHAR(255),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT "notification_templates_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_notification_templates_code" UNIQUE ("template_code")
);
