-- liquibase formatted sql

-- changeset sameerkhan:sync_missing_tables
CREATE TABLE IF NOT EXISTS "reports" (
                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         "report_id" VARCHAR(255) NOT NULL,
    "report_name" VARCHAR(255) NOT NULL,
    "report_type" VARCHAR(255),
    "format" VARCHAR(255),
    "generated_by" BIGINT,
    "generated_date" TIMESTAMP WITH TIME ZONE,
    "start_date" TIMESTAMP WITH TIME ZONE,
    "end_date" TIMESTAMP WITH TIME ZONE,
                             "description" VARCHAR(1000),
    "file_path" VARCHAR(255),
    "file_url" VARCHAR(255),
    "file_size" BIGINT,
    "is_scheduled" BOOLEAN DEFAULT FALSE NOT NULL,
    "schedule_cron" VARCHAR(255),
    "next_scheduled_date" TIMESTAMP WITH TIME ZONE,
                             "recipients" VARCHAR(255),
    "download_count" INTEGER DEFAULT 0 NOT NULL,
    "status" VARCHAR(50),
    "error_message" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT "reports_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_reports_report_id" UNIQUE ("report_id")
    );

CREATE TABLE IF NOT EXISTS "report_parameters" (
                                                   "report_id" BIGINT NOT NULL,
                                                   "param_key" VARCHAR(255) NOT NULL,
    "param_value" VARCHAR(500),
    CONSTRAINT "report_parameters_pkey" PRIMARY KEY ("report_id", "param_key"),
    CONSTRAINT "fk_report_parameters_report" FOREIGN KEY ("report_id") REFERENCES "reports" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS "platform_incident" (
                                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                   "incident_number" VARCHAR(80) NOT NULL,
    "organization_id" BIGINT,
    "subject_type" VARCHAR(30) NOT NULL,
    "incident_type" VARCHAR(40) NOT NULL,
    "severity" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "description" TEXT,
    "product_id" BIGINT,
    "store_product_id" BIGINT,
    "service_ticket_id" BIGINT,
    "warranty_claim_id" BIGINT,
    "reported_by" VARCHAR(150),
    "recommended_action" VARCHAR(60),
    "action_taken" VARCHAR(60),
    "resolution_notes" TEXT,
    "opened_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "resolved_at" TIMESTAMP WITH TIME ZONE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "created_by" BIGINT,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_by" BIGINT,
    CONSTRAINT "platform_incident_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_platform_incident_number" UNIQUE ("incident_number")
    );

CREATE TABLE IF NOT EXISTS "stock_count_session" (
                                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                     "organization_id" BIGINT NOT NULL,
                                                     "branch_id" BIGINT NOT NULL,
                                                     "warehouse_id" BIGINT NOT NULL,
                                                     "count_number" VARCHAR(80) NOT NULL,
    "count_date" DATE NOT NULL,
    "status" VARCHAR(30) NOT NULL,
    "notes" TEXT,
    "started_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "submitted_at" TIMESTAMP WITH TIME ZONE,
    "variance_posted_at" TIMESTAMP WITH TIME ZONE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "created_by" BIGINT,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updated_by" BIGINT,
    CONSTRAINT "stock_count_session_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_stock_count_session_number" UNIQUE ("count_number")
    );

-- changeset sameerkhan:sync_missing_columns
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "governance_status" VARCHAR(30) DEFAULT 'ACTIVE' NOT NULL;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "quality_review_status" VARCHAR(30) DEFAULT 'NORMAL' NOT NULL;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "block_new_store_adoption" BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "block_transactions" BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "governance_reason" TEXT;
ALTER TABLE "product" ADD COLUMN IF NOT EXISTS "governance_updated_at" TIMESTAMP WITH TIME ZONE;

ALTER TABLE "expense" ADD COLUMN IF NOT EXISTS "due_date" DATE;
ALTER TABLE "expense" ADD COLUMN IF NOT EXISTS "payment_method" VARCHAR(30);

ALTER TABLE "purchase_receipt" ADD COLUMN IF NOT EXISTS "due_date" DATE;
ALTER TABLE "purchase_receipt" ADD COLUMN IF NOT EXISTS "putaway_status" VARCHAR(30);
ALTER TABLE "purchase_receipt" ADD COLUMN IF NOT EXISTS "putaway_completed_at" TIMESTAMP WITH TIME ZONE;

ALTER TABLE "sales_order" ADD COLUMN IF NOT EXISTS "expected_fulfillment_by" DATE;

ALTER TABLE "inventory_batch" ADD COLUMN IF NOT EXISTS "batch_type" VARCHAR(30) DEFAULT 'EXTERNAL_BATCH' NOT NULL;
ALTER TABLE "inventory_batch" ADD COLUMN IF NOT EXISTS "purchase_unit_cost" NUMERIC(18,2);
ALTER TABLE "inventory_batch" ADD COLUMN IF NOT EXISTS "suggested_sale_price" NUMERIC(18,2);
ALTER TABLE "inventory_batch" ADD COLUMN IF NOT EXISTS "mrp" NUMERIC(18,2);